apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: payment 
  namespace: roboshop 
  labels: 
    app: payment 
    tier: app 
    project: roboshop 
spec: 
  replicas: 1   
  selector: 
    matchLabels: 
      app: payment
      tier: app
      project: roboshop 
  template: 
    metadata: 
      labels: 
        app: payment 
        tier: app 
        project: roboshop 
    spec: 
      containers: 
      - name: payment 
        image: akarapunikhilchandra/payment:1.0.0
        envFrom: 
        - configMapRef: 
            name: payment 
--- 
apiVersion: v1 
kind: Service
metadata: 
  name: payment 
  namespace: roboshop 
spec: 
  selector:   
    app: payment 
    tier: app 
    project: roboshop 
  ports: 
  - name: mongodb-port 
    protocol: TCP 
    port: 8080 
    targetPort: 8080 
--- 
apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: payment 
  namespace: roboshop 
data: 
  AMQP_USER: "roboshop" 
  AMQP_PASS: "roboshop123"